baseURL = "https://quasaris.co/"
languageCode = "en-uk"
title = "Quasaris"
theme = "hello-friend-ng"
paginate = 10

[params]
  dateform = "2 Jan 2006"
  dateformShort = "2 Jan"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  # Subtitle for home
  homeSubTitle = "Something powerful is coming"

  # Set disableReadOtherPosts to true in order to hide the links to other posts
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Quasaris Group official website"
  keywords = "quasaris"
  images = [""]

[txonomies]
  # category = "blog"
  # tag = "tags"
  # series = "series"

[languages]
  [languages.en]
    title = "Quasaris"
    subtitle = "Something powerful is coming"
    keywords = ""
    copyright = "©2021 Quasaris Group"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Quasaris"
      logoHomeLink = "/"
    # or
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  #[[menu.main]]
  #  identifier = "blog"
  #  name = "Blog"
  #  url = "/posts"
